// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxiGCRn-E4y3iEFYLYDINHQ02WHAKaf6w',
    appId: '1:914425026723:web:a96b3f9273d24a58b7c716',
    messagingSenderId: '914425026723',
    projectId: 'mandir1008',
    authDomain: 'mandir1008.firebaseapp.com',
    storageBucket: 'mandir1008.appspot.com',
    measurementId: 'G-NBBTR35SPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByo-vqd6Pe4Y7LowZQfSNjWBHeq9Tz3Pw',
    appId: '1:914425026723:android:06b4ca9bd82f65bcb7c716',
    messagingSenderId: '914425026723',
    projectId: 'mandir1008',
    storageBucket: 'mandir1008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCel1fDvbp7QkpAXiwbCPVWqAd4_rlY5B4',
    appId: '1:914425026723:ios:7fe52f4c2f8757e1b7c716',
    messagingSenderId: '914425026723',
    projectId: 'mandir1008',
    storageBucket: 'mandir1008.appspot.com',
    iosClientId: '914425026723-hcbdav6gkpoh136mat0o6d28b82950fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCel1fDvbp7QkpAXiwbCPVWqAd4_rlY5B4',
    appId: '1:914425026723:ios:7fe52f4c2f8757e1b7c716',
    messagingSenderId: '914425026723',
    projectId: 'mandir1008',
    storageBucket: 'mandir1008.appspot.com',
    iosClientId: '914425026723-hcbdav6gkpoh136mat0o6d28b82950fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mandir',
  );
}
